# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2022-04-23T16:52:09+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Datum(BaseModel):
    SepalLength: float
    SepalWidth: float
    PetalLength: float
    PetalWidth: float


class Inputdata(BaseModel):
    data: List[Datum]
