# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2022-04-23T16:52:09+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class PredictionItem(BaseModel):
    Species: str


class Outputdata(BaseModel):
    prediction: List[PredictionItem]
