# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2022-04-23T16:52:09+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Datum(BaseModel):
    CRIM: float
    ZN: float
    INDUS: float
    CHAS: float
    NOX: float
    RM: float
    AGE: float
    DIS: float
    RAD: float
    TAX: float
    PTRATIO: float
    B: float
    LSTAT: float


class Inputdata(BaseModel):
    data: List[Datum]
